### ISSUE TITLE
Theme player UI colors

### ISSUE THREAD

**Issue by stephanrenggli** [lscambo13/ElegantFin#31]
**Is your feature request related to a problem? Please describe.**
The player UI colors are not yet themed.

![image](https://github.com/user-attachments/assets/237e5695-64b2-42ec-b6c3-695054aee369)

The following elements do not seem to be themed with the colors used for other UI elements:
- Progress bar and bubble
- Volume slider and bubble
- Volume overlay bar when changing the volume

**Describe the solution you'd like**
The player UI colors should be themed the same as other UI elements.

The dashboard uses `var(--btnSubmitBorderColor)` for the progress bars, so I think the player sliders and progress bar should use the same color.

**Describe alternatives you've considered**
Add required changes myself.

**Additional context**

**Comment by stephanrenggli** [comment]
I added the relevant CSS changes to my Jellyfin custom CSS:

```css
@import url("https://cdn.jsdelivr.net/gh/lscambo13/ElegantFin@main/Theme/ElegantFin-jellyfin-theme-build-latest-minified.css");

/* Adjust progress and volume bar color */
.mdl-slider-background-lower {
  background-color: var(--btnSubmitBorderColor);
}

/* Adjust chapter marker color */
.sliderMarker.watched {
    background-color: var(--btnSubmitBorderColor);
}

/* Adjust OSD volume slider color */
.iconOsdProgressInner {
    background: var(--btnSubmitBorderColor);
}

/* Adjust slider circle color for chrome */
.mdl-slider::-webkit-slider-thumb {
  background: var(--btnSubmitBorderColor);
}

/* Adjust slider circle color for firefox */
.mdl-slider::-moz-range-thumb {
  background: var(--btnSubmitBorderColor);
}
```

Result:

![image](https://github.com/user-attachments/assets/b94dc076-1507-40c7-8368-6f7fe44d7f73)

Works on Chrome and Firefox, not tested on anything else.
