### ISSUE TITLE
Add support for the Media Bar plugin

### ISSUE THREAD

**Issue by Wernouxe** [lscambo13/ElegantFin#54]
**Is your feature request related to a problem? Please describe.**
possible to adapt the theme to this plugin?
https://github.com/IAmParadox27/jellyfin-plugin-media-bar

**Additional context**
it's a plugin that adds a “section” to suggest things to look at!

**Comment by lscambo13** [comment]
It seems like a good plugin. I've installed the repo and the plugin, and restarted the server, but it didn't change anything for me even on the stock theme. 

Do I need to take some extra steps to get it to show up?

**Comment by Wernouxe** [comment]
Add https://www.iamparadox.dev/jellyfin/plugins/manifest.json to your repositories
Install "File Transformation" at least 2.2.1.0
Install latest "Media Bar"
Restart Jellyfin

**Comment by lscambo13** [comment]
Got it working now. I had missed the second step. 

I like it so far, and I might keep using it. Here's how it looks with some fixes on our theme:

![Image](https://github.com/user-attachments/assets/4144ab18-c920-4899-9ecd-4169d3281683)

![Image](https://github.com/user-attachments/assets/dfad85ba-3b9d-4a01-acc8-6237b514f913)

I'll try to include support for it in the next update.

**Comment by Wernouxe** [comment]
wow, it looks great!

**Comment by Jordan-4** [comment]
it looks so cool, but the 'more info' and 'play' button need some improvements imo

**Comment by Wernouxe** [comment]
for my part, I've tried to do something (well, it's probably not very optimized, but if it can give you an idea):
![Image](https://github.com/user-attachments/assets/271f6eaa-bce2-4962-a1e8-2a97bc4ab6ee)

```css
.button-container {
  gap: 10px;
}
.button-container button.detailButton,
.favorite-button {
  border-radius: var(--smallRadius);
  border: var(--defaultLighterBorder);
  padding: 0.5em !important;
  margin: 0.125em !important;
  backdrop-filter: var(--blurSmallest);
  background-color: rgba(255, 255, 255, 0.05);
  color: inherit;
}
.button-container button.detailButton.play-button {
  padding: 0.5em 1em !important;
}
@media (hover: hover) and (pointer: fine) {
  .button-container button.detailButton:hover,
  .favorite-button {
    background-color: rgba(255, 255, 255, 0.2);
    color: white;
    filter: brightness(1.2) !important;
  }
}

.favorite-button::before {
  content: "\e87d";
}
.button-container button::before {
  font-weight: 1 !important;
}
.detail-button::before {
  content: "\e88e";
}
.material-icons.play_arrow:before {
  content: "\e037";
}

.backdrop-container,
.backdrop,
.gradient-overlay {
  -webkit-mask-image: linear-gradient(
    to top,
    transparent,
    rgba(29, 38, 53, 0.8)
  );
}
.backdrop-container {
  -webkit-mask-image: linear-gradient(
    to top,
    transparent 0%,
    rgba(29, 38, 53, 0.8) 50%,
    rgba(29, 38, 53, 0.8) 60%
  ) !important;
}
.backdrop {
  -webkit-mask-image: linear-gradient(
    to top,
    transparent 10%,
    rgba(29, 38, 53, 0.8) 60%,
    rgba(29, 38, 53, 0.8) 70%
  ) !important;
}
.gradient-overlay {
  -webkit-mask-image: linear-gradient(
    to top,
    transparent 70%,
    rgba(29, 38, 53, 0.8) 90%,
    rgba(29, 38, 53, 0.8) 100%
  ) !important;
}
```

**Comment by gbomacfly** [comment]
Looks very nice! Do want :)

**Comment by lscambo13** [comment]
A new update to ElegantFin is available. 

Check it out and the experimental support plugin for the Media Bar from [here](https://github.com/lscambo13/ElegantFin#-how-to-customise-this-theme).

**Comment by quillfires** [comment]
<img width="1900" height="854" alt="Image" src="https://github.com/user-attachments/assets/9e30580c-0919-4f2b-9357-90075a5efd39" />

```css
#slides-container { height: 90% !important; }
#slides-container .favorite-button { display: none !important; }
#slides-container .detailButton {
    background-color: rgba(255, 255, 255, .15) !important;
    color: white !important;
    border-color: unset !important;
    height: 2.75em !important;
    margin-top: auto !important;
    margin-bottom: auto !important;
}
```
